from django.urls import path

from . import api, manager_views, views

urlpatterns = [
    path("", views.landing, name="landing"),
    path("accounts/register/", views.register_customer, name="register"),
    path("accounts/verify/<str:token>/", views.verify_email, name="verify_email"),
    path("accounts/resend-verification/", views.resend_verification, name="resend_verification"),
    path("health/", views.health, name="health"),
    path("manifest.webmanifest", views.manifest, name="manifest"),
    path("sw.js", views.service_worker, name="service_worker"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("location/select/", views.select_location, name="select_location"),
    path("customer/", views.customer_dashboard, name="customer_dashboard"),
    path("customer/payments/<uuid:payment_id>/confirm/", views.customer_confirm_payment, name="customer_confirm_payment"),
    path("customer/reviews/<uuid:location_id>/complete/", views.mark_reviewed, name="mark_reviewed"),
    path("bills/<uuid:entry_id>/", views.bill_detail, name="bill_detail"),
    path("staff/", views.staff_dashboard, name="staff_dashboard"),
    path("staff/charge/", views.staff_charge, name="staff_charge"),
    path("manager/", views.manager_dashboard, name="manager_dashboard"),
    path("manager/settings/", views.manager_settings, name="manager_settings"),
    path("manager/notifications/<int:notification_id>/read/", views.mark_notification_read, name="mark_notification_read"),
    path("manager/wallets/create/", views.manager_wallet_create, name="manager_wallet_create"),
    path("manager/wallets/scan/", manager_views.manager_wallet_scan, name="manager_wallet_scan"),
    path("manager/wallets/<uuid:wallet_id>/", views.manager_wallet_detail, name="manager_wallet_detail"),
    path("manager/wallets/<uuid:wallet_id>/topup/", views.manager_topup, name="manager_topup"),
    path("manager/wallets/<uuid:wallet_id>/refund/", views.manager_refund, name="manager_refund"),
    path("manager/wallets/<uuid:wallet_id>/status/", views.manager_wallet_status, name="manager_wallet_status"),
    path("api/v1/me/", api.MeView.as_view(), name="api_me"),
    path("api/v1/locations/", api.LocationsView.as_view(), name="api_locations"),
    path("api/v1/offers/", api.OffersView.as_view(), name="api_offers"),
    path("api/v1/wallet/", api.MyWalletView.as_view(), name="api_wallet"),
    path("api/v1/wallet/transactions/", api.MyTransactionsView.as_view(), name="api_wallet_transactions"),
    path("api/v1/payments/pending/", api.PendingPaymentsView.as_view(), name="api_pending_payments"),
    path("api/v1/payments/<uuid:payment_id>/confirm/", api.ConfirmPaymentView.as_view(), name="api_confirm_payment"),
    path("api/v1/notifications/", api.NotificationsView.as_view(), name="api_notifications"),
    path("api/v1/push-devices/", api.PushDeviceView.as_view(), name="api_push_devices"),
    path("api/v1/staff/charge/", api.StaffChargeView.as_view(), name="api_staff_charge"),
    path("api/v1/manager/topup/", api.ManagerTopupView.as_view(), name="api_manager_topup"),
    path("api/v1/manager/refund/", api.ManagerRefundView.as_view(), name="api_manager_refund"),
]
