# Generated by Django 5.2 for the SAMS compliance hardening release.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cards", "0010_native_push_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestWalletMarker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_test_wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="test_data_marker",
                        to="cards.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testkonto-Markierung",
                "verbose_name_plural": "Testkonto-Markierungen",
                "ordering": ["-created_at"],
            },
        ),
    ]
